version: '3.8'

services:
  # PostgreSQL database for main application data
  postgres:
    image: postgres:15-alpine
    container_name: callcenter-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-callcenter}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d callcenter"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Qdrant vector database for semantic search
  qdrant:
    image: qdrant/qdrant:latest
    container_name: callcenter-qdrant
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      QDRANT_ALLOW_CORS: "true"

  # Neo4j graph database for context relationships
  neo4j:
    image: neo4j:enterprise
    container_name: callcenter-neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc", "apoc-extended"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

  # Redis for caching and message broker
  redis:
    image: redis:7-alpine
    container_name: callcenter-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  # Elasticsearch for full-text search and logging
  elasticsearch:
    image: elasticsearch:8.10.4
    container_name: callcenter-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # FastAPI application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: callcenter-app
    restart: always
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - qdrant
      - neo4j
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/callcenter
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
  qdrant_data:
  neo4j_data:
  neo4j_logs:
  redis_data:
  elasticsearch_data: 